import scrapy


class AutoItem(scrapy.Item):
    make = scrapy.Field()
    model = scrapy.Field()
    marketing_headline = scrapy.Field()
    sales_price_incl_vat = scrapy.Field()
    sales_price_excl_vat = scrapy.Field()
    currency = scrapy.Field()
    body_type = scrapy.Field()
    mileage = scrapy.Field()
    cubic_capacity = scrapy.Field()
    power_in_kw = scrapy.Field()
    power_in_ps = scrapy.Field()
    fuel = scrapy.Field()
    fuel_consumption_comb = scrapy.Field()
    fuel_consumption_city = scrapy.Field()
    fuel_consumption_country = scrapy.Field()
    co2_emission = scrapy.Field()
    energy_efficiency_class = scrapy.Field()
    number_of_seats = scrapy.Field()
    number_of_doors = scrapy.Field()
    gearbox = scrapy.Field()
    emission_class = scrapy.Field()
    first_registration = scrapy.Field()
    number_of_previous_owners = scrapy.Field()
    service_maintenance = scrapy.Field()
    climate_control = scrapy.Field()
    parking_sensors = scrapy.Field()
    airbags = scrapy.Field()
    colour = scrapy.Field()
    interior = scrapy.Field()
    id = scrapy.Field()